font_family      Maple Mono NF
font_size        10

adjust_line_height  0
adjust_column_width 0
background #1C1B22
background_opacity 0.8
selection_foreground #000000
selection_background #5daca2

confirm_os_window_close 0